[package]
name = "shapekit"
version = "0.4.0"
authors = ["joshua"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ordtags = { git = "https://github.com/treetertot/ordtags" }